export type FreshdeskWebhook = {
  ticket_id: number;
  ticket_subject: string;
  ticket_description: string;
  ticket_url: string;
  ticket_portal_url?: string;
  ticket_tags?: string;
  ticket_latest_public_comment?: string;
  ticket_latest_private_comment?: string;
  ticket_group_name?: string | null;
  ticket_agent_name?: string | null;
  ticket_agent_email?: string | null;
  ticket_satisfaction_survey?: string;
  ticket_due_by_time?: string;
  ticket_status?: string;
  ticket_priority?: string;
  ticket_source?: string;
  ticket_ticket_type?: string | null;
  helpdesk_name?: string;
  ticket_portal_name?: string;
  ticket_product_description?: string | null;
  triggered_event?: string;
  ticket_company_name?: string;
  ticket_company_description?: string;
  ticket_company_note?: string;
  ticket_company_domains?: string;
  ticket_company_health_score?: number | null;
  ticket_company_account_tier?: string | null;
  ticket_company_renewal_date?: string | null;
  ticket_company_industry?: string | null;
  ticket_contact_name?: string;
  ticket_contact_firstname?: string;
  ticket_contact_lastname?: string;
  ticket_contact_mobile?: string | null;
  ticket_contact_email: string;
  ticket_contact_phone?: string | null;
  ticket_contact_address?: string;
  ticket_contact_unique_external_id?: string | null;
};
